### ISSUE TITLE
Docker instances are not configure for auto restart

### ISSUE THREAD

**Issue by biorosetics** [Candihub/pixel#121]
After reboot, pixel docker instances do not restart automatically.

**Comment by jmaupetit** [comment]
Thx for the report. I remember having chatted about this with @willdurand and forgot to declare an issue… my bad.

AFAIU, as stated in [docker-compose documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#restart), we need to add the `restart: always` instruction to services that need to auto restart, right?

```yaml
services:
  db:
    # [...]
    restart: always

  web:
    # [...]
    restart: always
    
  proxy:
    # [...]
    restart: always
    
# [...]
```

**Comment by willdurand** [comment]
Yes, I think we should add `restart` and maybe a `retry` or `max_retry` (dont recall the exact name) to avoid restarting failing containers indefinitely.

**Comment by jmaupetit** [comment]
I think this condition has been introduced in the version 3 of docker compose file (we use 2.1): https://docs.docker.com/compose/compose-file/#restart_policy

**Comment by jmaupetit** [comment]
@biorosetics I checked `docker` and `docker-compose` releases, and I think you've upgraded them, am I right?

```
$ docker -v
Docker version 17.12.0-ce, build c97c6d6
$ docker-compose -v
docker-compose version 1.17.1, build 6d101fb
```

So it looks like we can use the version 3 of docker compose file.

**Comment by jmaupetit** [comment]
The `restart_policy` configuration is only accessible in swarm mode with `docker stack deploy`. So I think my first idea to add `restart: always` is the way to go to avoid loosing time in switching to docker swarm.

**Comment by willdurand** [comment]
I was referring to `retries`

**Comment by jmaupetit** [comment]
Like the [`healthckeck`'s `retries`](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck)? 

```yaml
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 40s
```
