### ISSUE TITLE
Pixel sets exportation tool

### ISSUE THREAD

**Issue by jmaupetit** [Candihub/pixel#144]
## Purpose

The pixel sets explorer ultimate purpose is to export a selection of pixel sets. Let's implement this small tool before plugin it to the interface.

## Proposal

Develop a new utility that takes a set of `PixelSet`s as input and generates a zip archive containing pixels in a csv file and a separated meta file:

```
foo.zip
└── foo
    ├── pixels.csv
    └── meta.yaml
```

### Example 

```csv
# Pixels.csv
OmicsUnit; val1; IC1; val2; IC2
foo; 4.2; 0.56; NA; NA
bar; 5.8; 0.99; 3.4; 0.67
baz; NA; NA; 1.4; 0.10
```

👆 in this case the `bar` Omics Unit has pixels in both the first and second pixel sets where `foo` has pixels in the first pixel set and `baz` only in the second.

```yaml
# meta.yaml
pixelsets:
  - pixelset: ff3600e
    description: lorem ipsum
    columns:
      - 1
      - 2
  - pixelset: ff18fdc
    description: lorem ipsum
    columns:
      - 3
      - 4
```

Note that the utility signature must provide a way to write in a custom file handler (StringIO or HTTP response):

```python
def export_pixelsets(pixelsets, output=None):
    pass
```
